sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build zef
  - zef --depsonly install .

script:
  - AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib"
  - zef install .
